apiVersion: v1
kind: Service
metadata:
  name: outline
  namespace: outline
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: outline
  ports:
    - port: 3000          # port interne du service (et du pod)
      targetPort: 3000    # port sur lequel le pod écoute
      nodePort: 31081 